export const ADD_LOCATAIRE = 'ADD_LOCATAIRE';
export const UPDATE_LOCATAIRE = 'UPDATE_LOCATAIRE';
export const DELETE_LOCATAIRE = 'DELETE_LOCATAIRE';
export const FILTRER_LOCATAIRE = 'FILTRER_LOCATAIRE';
export const CLEAR_FILTER = 'CLEAR_FILTER';
